/**
 * Reference list of sovereign countries used across the app.
 *
 * `code` is the lowercase ISO 3166-1 alpha-2 code, matching the `id` field
 * used by the `@svg-maps/world` dataset so the map and the list/stats views
 * stay in sync.
 */

export type Continent =
  | 'Africa'
  | 'Asia'
  | 'Europe'
  | 'North America'
  | 'South America'
  | 'Oceania';

export type Country = {
  code: string;
  name: string;
  continent: Continent;
};

export const COUNTRIES: Country[] = [
  // Africa
  { code: 'dz', name: 'Algeria', continent: 'Africa' },
  { code: 'ao', name: 'Angola', continent: 'Africa' },
  { code: 'bj', name: 'Benin', continent: 'Africa' },
  { code: 'bw', name: 'Botswana', continent: 'Africa' },
  { code: 'bf', name: 'Burkina Faso', continent: 'Africa' },
  { code: 'bi', name: 'Burundi', continent: 'Africa' },
  { code: 'cm', name: 'Cameroon', continent: 'Africa' },
  { code: 'cv', name: 'Cape Verde', continent: 'Africa' },
  { code: 'cf', name: 'Central African Republic', continent: 'Africa' },
  { code: 'td', name: 'Chad', continent: 'Africa' },
  { code: 'km', name: 'Comoros', continent: 'Africa' },
  { code: 'cg', name: 'Congo', continent: 'Africa' },
  { code: 'cd', name: 'DR Congo', continent: 'Africa' },
  { code: 'ci', name: "Cote d'Ivoire", continent: 'Africa' },
  { code: 'dj', name: 'Djibouti', continent: 'Africa' },
  { code: 'eg', name: 'Egypt', continent: 'Africa' },
  { code: 'gq', name: 'Equatorial Guinea', continent: 'Africa' },
  { code: 'er', name: 'Eritrea', continent: 'Africa' },
  { code: 'sz', name: 'Eswatini', continent: 'Africa' },
  { code: 'et', name: 'Ethiopia', continent: 'Africa' },
  { code: 'ga', name: 'Gabon', continent: 'Africa' },
  { code: 'gm', name: 'Gambia', continent: 'Africa' },
  { code: 'gh', name: 'Ghana', continent: 'Africa' },
  { code: 'gn', name: 'Guinea', continent: 'Africa' },
  { code: 'gw', name: 'Guinea-Bissau', continent: 'Africa' },
  { code: 'ke', name: 'Kenya', continent: 'Africa' },
  { code: 'ls', name: 'Lesotho', continent: 'Africa' },
  { code: 'lr', name: 'Liberia', continent: 'Africa' },
  { code: 'ly', name: 'Libya', continent: 'Africa' },
  { code: 'mg', name: 'Madagascar', continent: 'Africa' },
  { code: 'mw', name: 'Malawi', continent: 'Africa' },
  { code: 'ml', name: 'Mali', continent: 'Africa' },
  { code: 'mr', name: 'Mauritania', continent: 'Africa' },
  { code: 'mu', name: 'Mauritius', continent: 'Africa' },
  { code: 'ma', name: 'Morocco', continent: 'Africa' },
  { code: 'mz', name: 'Mozambique', continent: 'Africa' },
  { code: 'na', name: 'Namibia', continent: 'Africa' },
  { code: 'ne', name: 'Niger', continent: 'Africa' },
  { code: 'ng', name: 'Nigeria', continent: 'Africa' },
  { code: 'rw', name: 'Rwanda', continent: 'Africa' },
  { code: 'st', name: 'Sao Tome and Principe', continent: 'Africa' },
  { code: 'sn', name: 'Senegal', continent: 'Africa' },
  { code: 'sc', name: 'Seychelles', continent: 'Africa' },
  { code: 'sl', name: 'Sierra Leone', continent: 'Africa' },
  { code: 'so', name: 'Somalia', continent: 'Africa' },
  { code: 'za', name: 'South Africa', continent: 'Africa' },
  { code: 'ss', name: 'South Sudan', continent: 'Africa' },
  { code: 'sd', name: 'Sudan', continent: 'Africa' },
  { code: 'tz', name: 'Tanzania', continent: 'Africa' },
  { code: 'tg', name: 'Togo', continent: 'Africa' },
  { code: 'tn', name: 'Tunisia', continent: 'Africa' },
  { code: 'ug', name: 'Uganda', continent: 'Africa' },
  { code: 'zm', name: 'Zambia', continent: 'Africa' },
  { code: 'zw', name: 'Zimbabwe', continent: 'Africa' },

  // Asia
  { code: 'af', name: 'Afghanistan', continent: 'Asia' },
  { code: 'am', name: 'Armenia', continent: 'Asia' },
  { code: 'az', name: 'Azerbaijan', continent: 'Asia' },
  { code: 'bh', name: 'Bahrain', continent: 'Asia' },
  { code: 'bd', name: 'Bangladesh', continent: 'Asia' },
  { code: 'bt', name: 'Bhutan', continent: 'Asia' },
  { code: 'bn', name: 'Brunei', continent: 'Asia' },
  { code: 'kh', name: 'Cambodia', continent: 'Asia' },
  { code: 'cn', name: 'China', continent: 'Asia' },
  { code: 'cy', name: 'Cyprus', continent: 'Asia' },
  { code: 'ge', name: 'Georgia', continent: 'Asia' },
  { code: 'in', name: 'India', continent: 'Asia' },
  { code: 'id', name: 'Indonesia', continent: 'Asia' },
  { code: 'ir', name: 'Iran', continent: 'Asia' },
  { code: 'iq', name: 'Iraq', continent: 'Asia' },
  { code: 'il', name: 'Israel', continent: 'Asia' },
  { code: 'jp', name: 'Japan', continent: 'Asia' },
  { code: 'jo', name: 'Jordan', continent: 'Asia' },
  { code: 'kz', name: 'Kazakhstan', continent: 'Asia' },
  { code: 'kw', name: 'Kuwait', continent: 'Asia' },
  { code: 'kg', name: 'Kyrgyzstan', continent: 'Asia' },
  { code: 'la', name: 'Laos', continent: 'Asia' },
  { code: 'lb', name: 'Lebanon', continent: 'Asia' },
  { code: 'my', name: 'Malaysia', continent: 'Asia' },
  { code: 'mv', name: 'Maldives', continent: 'Asia' },
  { code: 'mn', name: 'Mongolia', continent: 'Asia' },
  { code: 'mm', name: 'Myanmar', continent: 'Asia' },
  { code: 'np', name: 'Nepal', continent: 'Asia' },
  { code: 'kp', name: 'North Korea', continent: 'Asia' },
  { code: 'om', name: 'Oman', continent: 'Asia' },
  { code: 'pk', name: 'Pakistan', continent: 'Asia' },
  { code: 'ps', name: 'Palestine', continent: 'Asia' },
  { code: 'ph', name: 'Philippines', continent: 'Asia' },
  { code: 'qa', name: 'Qatar', continent: 'Asia' },
  { code: 'sa', name: 'Saudi Arabia', continent: 'Asia' },
  { code: 'sg', name: 'Singapore', continent: 'Asia' },
  { code: 'kr', name: 'South Korea', continent: 'Asia' },
  { code: 'lk', name: 'Sri Lanka', continent: 'Asia' },
  { code: 'sy', name: 'Syria', continent: 'Asia' },
  { code: 'tw', name: 'Taiwan', continent: 'Asia' },
  { code: 'tj', name: 'Tajikistan', continent: 'Asia' },
  { code: 'th', name: 'Thailand', continent: 'Asia' },
  { code: 'tl', name: 'Timor-Leste', continent: 'Asia' },
  { code: 'tr', name: 'Turkey', continent: 'Asia' },
  { code: 'tm', name: 'Turkmenistan', continent: 'Asia' },
  { code: 'ae', name: 'United Arab Emirates', continent: 'Asia' },
  { code: 'uz', name: 'Uzbekistan', continent: 'Asia' },
  { code: 'vn', name: 'Vietnam', continent: 'Asia' },
  { code: 'ye', name: 'Yemen', continent: 'Asia' },

  // Europe
  { code: 'al', name: 'Albania', continent: 'Europe' },
  { code: 'ad', name: 'Andorra', continent: 'Europe' },
  { code: 'at', name: 'Austria', continent: 'Europe' },
  { code: 'by', name: 'Belarus', continent: 'Europe' },
  { code: 'be', name: 'Belgium', continent: 'Europe' },
  { code: 'ba', name: 'Bosnia and Herzegovina', continent: 'Europe' },
  { code: 'bg', name: 'Bulgaria', continent: 'Europe' },
  { code: 'hr', name: 'Croatia', continent: 'Europe' },
  { code: 'cz', name: 'Czech Republic', continent: 'Europe' },
  { code: 'dk', name: 'Denmark', continent: 'Europe' },
  { code: 'ee', name: 'Estonia', continent: 'Europe' },
  { code: 'fi', name: 'Finland', continent: 'Europe' },
  { code: 'fr', name: 'France', continent: 'Europe' },
  { code: 'de', name: 'Germany', continent: 'Europe' },
  { code: 'gr', name: 'Greece', continent: 'Europe' },
  { code: 'hu', name: 'Hungary', continent: 'Europe' },
  { code: 'is', name: 'Iceland', continent: 'Europe' },
  { code: 'ie', name: 'Ireland', continent: 'Europe' },
  { code: 'it', name: 'Italy', continent: 'Europe' },
  { code: 'lv', name: 'Latvia', continent: 'Europe' },
  { code: 'li', name: 'Liechtenstein', continent: 'Europe' },
  { code: 'lt', name: 'Lithuania', continent: 'Europe' },
  { code: 'lu', name: 'Luxembourg', continent: 'Europe' },
  { code: 'mt', name: 'Malta', continent: 'Europe' },
  { code: 'md', name: 'Moldova', continent: 'Europe' },
  { code: 'mc', name: 'Monaco', continent: 'Europe' },
  { code: 'me', name: 'Montenegro', continent: 'Europe' },
  { code: 'nl', name: 'Netherlands', continent: 'Europe' },
  { code: 'mk', name: 'North Macedonia', continent: 'Europe' },
  { code: 'no', name: 'Norway', continent: 'Europe' },
  { code: 'pl', name: 'Poland', continent: 'Europe' },
  { code: 'pt', name: 'Portugal', continent: 'Europe' },
  { code: 'ro', name: 'Romania', continent: 'Europe' },
  { code: 'ru', name: 'Russia', continent: 'Europe' },
  { code: 'sm', name: 'San Marino', continent: 'Europe' },
  { code: 'rs', name: 'Serbia', continent: 'Europe' },
  { code: 'sk', name: 'Slovakia', continent: 'Europe' },
  { code: 'si', name: 'Slovenia', continent: 'Europe' },
  { code: 'es', name: 'Spain', continent: 'Europe' },
  { code: 'se', name: 'Sweden', continent: 'Europe' },
  { code: 'ch', name: 'Switzerland', continent: 'Europe' },
  { code: 'ua', name: 'Ukraine', continent: 'Europe' },
  { code: 'gb', name: 'United Kingdom', continent: 'Europe' },
  { code: 'va', name: 'Vatican City', continent: 'Europe' },

  // North America
  { code: 'ag', name: 'Antigua and Barbuda', continent: 'North America' },
  { code: 'bs', name: 'Bahamas', continent: 'North America' },
  { code: 'bb', name: 'Barbados', continent: 'North America' },
  { code: 'bz', name: 'Belize', continent: 'North America' },
  { code: 'ca', name: 'Canada', continent: 'North America' },
  { code: 'cr', name: 'Costa Rica', continent: 'North America' },
  { code: 'cu', name: 'Cuba', continent: 'North America' },
  { code: 'dm', name: 'Dominica', continent: 'North America' },
  { code: 'do', name: 'Dominican Republic', continent: 'North America' },
  { code: 'sv', name: 'El Salvador', continent: 'North America' },
  { code: 'gd', name: 'Grenada', continent: 'North America' },
  { code: 'gt', name: 'Guatemala', continent: 'North America' },
  { code: 'ht', name: 'Haiti', continent: 'North America' },
  { code: 'hn', name: 'Honduras', continent: 'North America' },
  { code: 'jm', name: 'Jamaica', continent: 'North America' },
  { code: 'mx', name: 'Mexico', continent: 'North America' },
  { code: 'ni', name: 'Nicaragua', continent: 'North America' },
  { code: 'pa', name: 'Panama', continent: 'North America' },
  { code: 'kn', name: 'Saint Kitts and Nevis', continent: 'North America' },
  { code: 'lc', name: 'Saint Lucia', continent: 'North America' },
  { code: 'vc', name: 'Saint Vincent and the Grenadines', continent: 'North America' },
  { code: 'tt', name: 'Trinidad and Tobago', continent: 'North America' },
  { code: 'us', name: 'United States', continent: 'North America' },

  // South America
  { code: 'ar', name: 'Argentina', continent: 'South America' },
  { code: 'bo', name: 'Bolivia', continent: 'South America' },
  { code: 'br', name: 'Brazil', continent: 'South America' },
  { code: 'cl', name: 'Chile', continent: 'South America' },
  { code: 'co', name: 'Colombia', continent: 'South America' },
  { code: 'ec', name: 'Ecuador', continent: 'South America' },
  { code: 'gy', name: 'Guyana', continent: 'South America' },
  { code: 'py', name: 'Paraguay', continent: 'South America' },
  { code: 'pe', name: 'Peru', continent: 'South America' },
  { code: 'sr', name: 'Suriname', continent: 'South America' },
  { code: 'uy', name: 'Uruguay', continent: 'South America' },
  { code: 've', name: 'Venezuela', continent: 'South America' },

  // Oceania
  { code: 'au', name: 'Australia', continent: 'Oceania' },
  { code: 'fj', name: 'Fiji', continent: 'Oceania' },
  { code: 'ki', name: 'Kiribati', continent: 'Oceania' },
  { code: 'mh', name: 'Marshall Islands', continent: 'Oceania' },
  { code: 'fm', name: 'Micronesia', continent: 'Oceania' },
  { code: 'nr', name: 'Nauru', continent: 'Oceania' },
  { code: 'nz', name: 'New Zealand', continent: 'Oceania' },
  { code: 'pw', name: 'Palau', continent: 'Oceania' },
  { code: 'pg', name: 'Papua New Guinea', continent: 'Oceania' },
  { code: 'ws', name: 'Samoa', continent: 'Oceania' },
  { code: 'sb', name: 'Solomon Islands', continent: 'Oceania' },
  { code: 'to', name: 'Tonga', continent: 'Oceania' },
  { code: 'tv', name: 'Tuvalu', continent: 'Oceania' },
  { code: 'vu', name: 'Vanuatu', continent: 'Oceania' },
];

export const COUNTRIES_BY_CODE: Record<string, Country> = COUNTRIES.reduce(
  (acc, country) => {
    acc[country.code] = country;
    return acc;
  },
  {} as Record<string, Country>
);

export const CONTINENTS: Continent[] = [
  'Africa',
  'Asia',
  'Europe',
  'North America',
  'South America',
  'Oceania',
];

export const TOTAL_COUNTRY_COUNT = COUNTRIES.length;
